version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  db_ui:
    image: dpage/pgadmin4:6.11
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=mkelly@synacksolutions.net
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "80:80"
    depends_on:
      - "db"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  keycloak:
    image: bitnami/keycloak:18
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - "db"
